apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-cloudrun
  namespace: default
  labels:
    app: test-app-cloudrun
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app-cloudrun
  template:
    metadata:
      labels:
        app: test-app-cloudrun
    spec:
      containers:
      - name: test-app-cloudrun
        image: asia-south1-docker.pkg.dev/dev-zephyr-352206/test-app-cloudrun/test-app-cloudrun:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: openweather-api-key
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-cloudrun-service
  namespace: default
spec:
  selector:
    app: test-app-cloudrun
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
